# site wide settings

title: Chung Research Group
locale: en_US
search: true
email: greg.chung[at]pusan.ac.kr
description: School of Chemical & Biomolecular Engineering, 7th Engineering Building, Busan Korea (South)

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gregchung.github.io" # the base hostname & protocol for your site
twitter_username: DrYGChung
github_username:  gregchung

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-66713824-1

# Flowery
permalink: pretty
