# site wide settings

title: Chung Research Group
locale: en_US
search: true
email: drygchung[at]gmail.com
description: School of Chemical & Biomolecular Engineering, 7th Engineering Building, Busan Korea (South)

baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
#markdown: kramdown
theme: minima
google_analytics: UA-66713824-1

# Flowery
permalink: pretty
